export const GROUP_STOCK_LIST = "GROUP_STOCK_LIST";
export const THREE_STOCK_LIST = "THREE_STOCK_LIST";
export const WALLET_TRANSECTION = "WALLET_TRANSECTION";
export const DB_AUTH_DATA = "DB_AUTH_DATA";
export const DB_GROUP_CHART_DATA = "DB_GROUP_CHART_DATA";
export const DB_THREE_CARD_CHART_DATA = "DB_THREE_CARD_CHART_DATA";
export const DB_GROUP_INVESTMENT_DATA = "DB_GROUP_INVESTMENT_DATA";
export const DB_THREE_CARD_INVESTMENT_DATA = "DB_THREE_CARD_INVESTMENT_DATA";
