export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_PERMISSION_SLUGS =
  "SET_CURRENT_USER_PERMISSION_SLUGS";
export const SET_CURRENT_USER_PERMISSION_MODULES =
  "SET_CURRENT_USER_PERMISSION_MODULES";
